pomp/pomp/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf import settings 
from django.conf.urls.static  import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('products.urls')) , 
    path('ckeditor/', include('ckeditor_uploader.urls')), 
]

if settings.DEBUG : 
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT  )

pomp/products/urls.py
from django.urls import path 
from .views import Total_product   , details_of_product , Text_original_page_views , newsletter 

app_name = "app1"
urlpatterns = [
    path("" , Total_product  , name = "Total_product" ) , 
    
    path("" , newsletter , name = "newsletter"  ) , 
    path("detail/<slug:slug>/<int:id>" , details_of_product , name="details_of_product" ) , 
    

    
]

pomp/services/urls.py
from django.url import path 

pomp/services/models.py
from django.db import models
from ckeditor.fields import RichTextField 
# Create your models here.


class services(models.Model) : 
    STATUS_CHOICES = (
        ('a' , 'فعال' )  , 
        ('d' , 'غیر فعال ') 
    )

    type_service_CHOICES = (
    
        ("bi bi-chat-left-dots"  , 'مشاوره' ) , 
        ("bi bi-bounding-box" , 'طراحی') , 
        ("bi bi-bounding-box" , 'نصب' ) , 
        ("bi bi-broadcast" , 'تعمیرات') , 
        ("bi bi-broadcast" , 'ساخت') 

    )


    name = models.CharField(verbose_name = "نام خدمت"  , max_length = 200 ) 

    slug = models.SlugField(verbose_name = "آدرس خدمت "  , max_length = 200 , unique = True ) 

    descriptions = RichTextField(verbose_name = "توضیحات خدمت" , null = True , blank = True )


    picture = models.FileField(upload_to = "Image_Services" , verbose_name = "عکس خدمت"  , blank = True , null = True ) 


    status = models.CharField(verbose_name = "وضعیت" , max_length =1 , choices = STATUS_CHOICES  )

    type_service = models.CharField(verbose_name = "نوع خدمت" , max_length =50 , choices = type_service_CHOICES  , null = True , blank = True )


    def __str__(self ) : 
        return self.name 

    class Meta : 
        db_table = "services"

        verbose_name_plural = "خدمات" 
        

    

pomp/services/views.py
from django.shortcuts import render

# Create your views here.

pomp/templates/website/Portfolio.html
<section id="portfolio" class="portfolio section-bg">
    <div class="container" data-aos="fade-up" data-aos-delay="100">

      <div class="section-title">
        <h2>پروژه و محصولات ما </h2>
        <p>پروژه ها و محصولات شرکت آبنوش قابل مشاهده میباشد </p>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">همه</li>
            <li data-filter=".filter-app">تابلو </li>
            <li data-filter=".filter-card">پمپ آب</li>
            
          </ul>
        </div>
      </div>

      <div class="row portfolio-container">
      {%  for i in obj %}
        <div class="{{i.type_product}}">
          <div class="portfolio-wrap">
            <img width = "50%" height = "auto" src="{{i.picture.url}}" class="img-fluid" alt="">
            <div class="portfolio-info">
              <h4>{{i.name}}</h4>

              <p>
                {%  if i.type_product == "col-lg-4 col-md-6 portfolio-item filter-app" %}
                  <p> تابلو </p>


                {%  else  %}

                  <p> پمپ </p>
              
              
                {%  endif %}
              </p>
              <div class="portfolio-links">
                <a href="{{i.picture.url}}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bi bi-plus"></i></a>
                <a href="{{i.get_absolute_url}}" title="More Details"><i class="bi bi-link"></i></a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}

















      </div>

    </div>
  </section>

pomp/templates/website/about_lists_section.html
<section class="about-lists">
    <div class="container">

      <div dir="rtl" class="row no-gutters">
        {%  for i in obj_text %}
        <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up">
          <span>{{i.number}}</span>
          <h4>{{i.head}}</h4>
          <p>{{i.body}}</p>
        </div>
        {%  endfor %}

      </div>

    </div>
  </section>

pomp/templates/website/about_us.html
<section id="about" class="about">
    <div class="container" data-aos="fade-up">

      <div class="row no-gutters">
        <div class="col-lg-6 video-box">
          <img src="assets/img/about.jpg" class="img-fluid" alt="">
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a>
        </div>

        <div class="col-lg-6 d-flex flex-column justify-content-center about-content">

          <div class="section-title">
            <h2>درباره ما </h2>
            <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.</p>
          </div>

          <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
            <div class="icon"><i class="bx bx-fingerprint"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
          </div>

          <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
            <div class="icon"><i class="bx bx-gift"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
          </div>

        </div>
      </div>

    </div>
  </section>

pomp/templates/website/asked_question.html
<section id="faq" class="faq section-bg">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>سوالات متداول</h2>
      </div>

      <div dir = "rtl" class="row  d-flex align-items-stretch">
        {%  for i in questions %}
        <div class="col-lg-6 faq-item" data-aos="fade-up">
          <h4>{{i.question}}</h4>
          <p>
            {{i.answer}}
          </p>
        </div>


        {%  endfor %}


      </div>

    </div>
  </section>

pomp/templates/website/contact1.html
<form method="post" > 
    {%  csrf_token %}

    {{form.full_name}}

    {{form.email}}

    {{form.subject}}


    {{form.message}}





    <button type="submit">ارسال</button>
</form>

pomp/templates/website/contact_us.html
<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>ارتباط با ما </h2>
      </div>

      <div class="row">

        <div class="col-lg-6 d-flex" data-aos="fade-up">
          <div class="info-box">
            <i class="bx bx-map"></i>
            <h3>آدرس ما </h3>
            {%  for i in obj_address  %}
            <p>{{i.address}}</p>
            {%  endfor %}
          </div>
        </div>

        <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="100">
          <div class="info-box">
            <i class="bx bx-envelope"></i>
            <h3>ایمیل ما </h3>
            {%  for i in obj_address %}
            <p>{{i.email}}</p>
            {%  endfor %}
          </div>
        </div>

        <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="200">
          <div class="info-box ">
            <i class="bx bx-phone-call"></i>
            <h3>تماس با ما </h3>
            {%  for i in obj_address %}
            <p>{{i.phone1}}<br>{{i.phone2}}</p>

            {%  empty %} 
            <p> شماره ای در حال حاضر آماده نیست </p>
            {%  endfor %}
          </div>
        </div>

        <div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">

         
          </form>

        </div>

      </div>

    </div>
  </section>

pomp/templates/website/counts_section.html
<section class="counts section-bg">
    <div class="container">

      <div class="row">

        <div class="col-lg-3 col-md-6 text-center" data-aos="fade-up">
          <div class="count-box">
            <i class="bi bi-simple-smile" style="color: #20b38e;"></i>
            <span data-purecounter-start="0" data-purecounter-end="{{count_project}}" data-purecounter-duration="1" class="purecounter"></span>
            <p>مشتزیان خوشحال</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 text-center" data-aos="fade-up" data-aos-delay="200">
          <div class="count-box">
            <i class="bi bi-document-folder" style="color: #c042ff;"></i>
            <span data-purecounter-start="0" data-purecounter-end="{{count_project}}" data-purecounter-duration="1" class="purecounter"></span>
            <p>تعداد پروژه ها ما </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 text-center" data-aos="fade-up" data-aos-delay="400">
          <div class="count-box">
            <i class="bi bi-live-support" style="color: #46d1ff;"></i>
            <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
            <p>Hours Of Support</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 text-center" data-aos="fade-up" data-aos-delay="600">
          <div class="count-box">
            <i class="bi bi-users-alt-5" style="color: #ffb459;"></i>
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
            <p>Hard Workers</p>
          </div>
        </div>

      </div>

    </div>
  </section>

pomp/templates/website/footer.html
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>شرکت آبنوش</h3>
            <p>
             ایران - تهران <br> 
             مترو سبلان - خیابان دماوند - روبه روی تالار قصر فراز 

              <br><br>
              <strong>تلفن:</strong>  09120985863 <br>
              <strong>ایمیل:</strong> alitalebishahroodi@gmail.com <br>
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>لینک ها </h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{%  url 'app1:Total_product' %}">خانه</a></li>
              <!-- <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li> -->
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'app1:Total_product' %}#services">خدمات</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'app1:Total_product' %}#portfolio"> پروژه ها  </a></li>
              
              
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>  خدمات ما   </h4>
            <ul>
              {% for i in obj_services  %}
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'app1:Total_product' %}#services">{{i.name}}</a></li>

              {%  endfor %}
            </ul>
          </div>

          <div  class="col-lg-4 col-md-6 footer-newsletter">
            <h4 dir = "rtl" >خبرنامه ما </h4>
            <p style = "font-size:20px" dir="rtl" > با عضویت در خبرنامه ما ، از محصولات جدید با خبر شوید </p>
            <form action="" method="post">
              {%  csrf_token %}

               
               <input name = "email_account" > 
                
              <input type="submit" value="عضویت"> 
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; تمامی حقوق متعلق به شرکت آبنوش میباشد 
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/ -->
        <br>
        طراح و پشتیبان : علی طالبی 
        <br>

         <a href="https://bootstrapmade.com/">استفاده از قالب بوت استرپ </a>
      </div>
    </div>
</footer>

pomp/templates/website/header.html
<header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo me-auto">
        <h1><a href="{%  url 'app1:Total_product' %}">شرکت آبنوش  </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{%  url 'app1:Total_product' %}">خانه</a></li>
          <!-- <li><a class="nav-link scrollto" href="#about">About</a></li> -->
          <li><a class="nav-link scrollto" href="{% url 'app1:Total_product' %}#services">خدمات ما</a></li>
          <li><a class="nav-link scrollto" href="{% url 'app1:Total_product' %}#portfolio">پروژه ها </a></li>
          <li><a class="nav-link scrollto" href="{% url 'app1:Total_product' %}#team">تیم ما</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">ارتباط با ما </a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>

pomp/templates/website/hero_section.html
{%  load static %}
<section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">


          {%  for i in picture %}
          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url({{i.picture.url}});">
            <div class="carousel-container">
              <div class="carousel-content container">
                {%  if i.sentence %}
                <h2 class="animate__animated animate__fadeInDown">  {{i.sentence}}   </h2>
                {%  else  %}
                <h2 class="animate__animated animate__fadeInDown">  به وبسایت  شرکت آبنوش خوش آمدید </h2>


                {%  endif %}
                <!-- <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p> -->
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">با لبخند وارد شوید </a>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->


          <!-- Slide 3 -->
          {%  endfor %}

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section>

pomp/templates/website/portfolio-details.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>جزئیات پروژه </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'website/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'website/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'website/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'website/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Mamba
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope-fill"></i><a href="mailto:alitalebishahroodi@gmail.com">alitalebishahroodi@gmail.com</a>
        <i class="bi bi-phone-fill phone-icon"></i> 09120985863 
      </div>
      <div class="social-links d-none d-md-block">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  {%  block header %}
  {%  include 'website/header.html' %}
  {%  endblock %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>جزئیات پروژه </h2>
          <ol>
            <li><a href="{%  url 'app1:Total_product' %}">خانه</a></li>
            <li><a href="{% url 'app1:Total_product' %}#portfolio">سبد محصولات و پروژه ها </a></li>
            <li> جزئیات پروژه </li>
          </ol>
        </div>

      </div>
    </section><!-- Breadcrumbs Section -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img style = "width:100%"  src="{{obj1.picture.url}}" alt="">
                </div>

                <div class="swiper-slide">
                  {%  if obj1.picture2 %}
                  <img style = "width:100%"  src="{{obj1.picture2.url}}" alt="">
                  {%  endif %}
                </div>

                <div class="swiper-slide">
                  {%  if obj1.picture3  %}
                  <img style = "width:100%"  src="{{obj1.picture3.url}}" alt="">
                  {%  endif %}
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div dir = "rtl" class="portfolio-info">
              <h3> اطلاعات </h3>
              <ul>
                <li><strong>دسته بندی </strong>{{obj1.category}}</li>
                <li><strong>مشتری</strong>: ASU Company</li>
                <li><strong>تاریخ پروژه  </strong>: 01 March, 2020</li>
                <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
              </ul>
            </div>
            <div dir = "rtl" class="portfolio-description">
              <h2>{{obj1.name |safe }}</h2>
              <p>
              {{obj1.descriptions |safe }}
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {%  block footer %}
  {%  include 'website/footer.html' %}
  {% endblock %}
  <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'website/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'website/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'website/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'website/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'website/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'website/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'website/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'website/assets/js/main.js' %}"></script>

</body>

</html>

pomp/templates/website/services.html
<section id="services" class="services">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>خدمات ما</h2>
      </div>

      <div class="row">

        {%  for i in obj_services %}

                

        

        
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
          <div class="icon"><i class= "{{i.type_service}}" ></i></div>
          <h4 class="title"><a href="">{{i.name}}</a></h4>
          <p class="description">{{i.description}}</p>
          
        </div>


  

        {%  empty %}
          <h4> <center> درحال حاضر هیچ خدمتی در دست اقدام نمیباشد </center> </h4>

        {%  endfor %}



      </div>

    </div>
  </section>